### ISSUE TITLE
Placeholder %team_displayname% not working

### ISSUE THREAD

**Issue by andriiqx** [Groovin-Dev/TeamsExpansion#4]
![Screenshot_7562](https://github.com/Groovin-Dev/TeamsExpansion/assets/116912308/7792f8fe-6976-40ba-a684-21ccf87a29cc)

**Comment by andriiqx** [comment]
can anyone fix this?

**Comment by Groovin-Dev** [comment]
I couldn't replicate this on MC 1.20.1 with Placeholder 2.11.5
![image](https://github.com/Groovin-Dev/TeamsExpansion/assets/56172528/6eb61cba-8c80-4da2-8e40-87d8158f0ad0)


Which MC version are you on?

**Comment by andriiqx** [comment]
> I couldn't replicate this on MC 1.20.1 with Placeholder 2.11.5 ![image](https://private-user-images.githubusercontent.com/56172528/327847396-6eb61cba-8c80-4da2-8e40-87d8158f0ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4ODk5ODMsIm5iZiI6MTcxNDg4OTY4MywicGF0aCI6Ii81NjE3MjUyOC8zMjc4NDczOTYtNmViNjFjYmEtOGM4MC00ZGEyLThlNDAtODdkODE1OGYwYWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA2MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiODQ0NDE5MTg4NDMxNmIzNjkyNWEzNTIwYmNiYzE4ZTI1NDMwMTQxZjQ4MzVhZTlkZDgxZmRkYTE4ZDNjY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sBvvKJc7lrMaatvtQrifQrORCpGhBJdgWsnUs8Mbvxo)
> 
> Which MC version are you on?

1.20.1, PAPI 2.11.5

org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.11.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[forge-1.20.1-47.2.30-universal.jar%23339!/:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[forge-1.20.1-47.2.30-universal.jar%23339!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:886) ~[forge-1.20.1-47.2.30-universal.jar%23339!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:51) ~[forge-1.20.1-47.2.30-universal.jar%23339!/:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.20.1.jar%23146!/:?]
        at net.minecraft.commands.Commands.m_242674_(Commands.java:318) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1874) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:1838) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1027) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1010) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1004) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:990) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:906) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23334!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component org.bukkit.scoreboard.Team.displayName()'
        at dev.groovin.teamsexpansion.PluginKt.getGetDisplayName(Plugin.kt:73) ~[?:?]
        at dev.groovin.teamsexpansion.PluginKt.access$getGetDisplayName(Plugin.kt:1) ~[?:?]
        at dev.groovin.teamsexpansion.TeamsExpansion.onRequest(Plugin.kt:32) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.5%20(1).jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.5%20(1).jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:117) ~[PlaceholderAPI-2.11.5%20(1).jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-2.11.5%20(1).jar:?]
        at me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-2.11.5%20(1).jar:?]

**Comment by Groovin-Dev** [comment]
Hey, sorry for the slow response I've been super busy. I see in your first screenshot that your command actually has 2 "%" at the end. Could you try that command again but with only one "%"?

If that works then I'll add some better error handling and parsing for that kind of issue when I get home

**Comment by andriiqx** [comment]
> Hey, sorry for the slow response I've been super busy. I see in your first screenshot that your command actually has 2 "%" at the end. Could you try that command again but with only one "%"?
> 
> If that works then I'll add some better error handling and parsing for that kind of issue when I get home

it doesn't work. papi 2.11.5:

        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[forge-1.20.1-47.2.32-universal.jar%23331!/:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[forge-1.20.1-47.2.32-universal.jar%23331!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:883) ~[forge-1.20.1-47.2.32-universal.jar%23331!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:867) ~[forge-1.20.1-47.2.32-universal.jar%23331!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at net.minecraft.server.dedicated.DedicatedServer.m_139665_(DedicatedServer.java:372) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:350) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component org.bukkit.scoreboard.Team.displayName()'
        at dev.groovin.teamsexpansion.PluginKt.getGetDisplayName(Plugin.kt:73) ~[?:?]
        at dev.groovin.teamsexpansion.PluginKt.access$getGetDisplayName(Plugin.kt:1) ~[?:?]
        at dev.groovin.teamsexpansion.TeamsExpansion.onRequest(Plugin.kt:32) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-2.11.6.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[forge-1.20.1-47.2.32-universal.jar%23331!/:?]
        ... 9 more
>

**Comment by Groovin-Dev** [comment]
Hmm, I'm not really sure what it could be. What is the team display name set to? Could you upload the full component? 
Could you try on a blank server with just PAPI and TeamsExpansion and see if that changes anything?

I tried to get it to error out like you said but even when a team doesn't exist it gracefully fails and just returns nothing

**Comment by andriiqx** [comment]
> Hmm, I'm not really sure what it could be. What is the team display name set to? Could you upload the full component? Could you try on a blank server with just PAPI and TeamsExpansion and see if that changes anything?
> 
> I tried to get it to error out like you said but even when a team doesn't exist it gracefully fails and just returns nothing

Not works.

        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:883) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:51) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.20.1.jar%23146!/:?]
        at net.minecraft.commands.Commands.m_242674_(Commands.java:321) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1871) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:1835) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1029) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1012) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1006) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:992) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:908) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component org.bukkit.scoreboard.Team.displayName()'
        at dev.groovin.teamsexpansion.PluginKt.getGetDisplayName(Plugin.kt:73) ~[?:?]
        at dev.groovin.teamsexpansion.PluginKt.access$getGetDisplayName(Plugin.kt:1) ~[?:?]
        at dev.groovin.teamsexpansion.TeamsExpansion.onRequest(Plugin.kt:32) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-2.11.6.jar:?]
        at me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-2.11.6.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:?]
        ... 22 more
>

**Comment by andriiqx** [comment]
> > Hmm, I'm not really sure what it could be. What is the team display name set to? Could you upload the full component? Could you try on a blank server with just PAPI and TeamsExpansion and see if that changes anything?
> > I tried to get it to error out like you said but even when a team doesn't exist it gracefully fails and just returns nothing
> 
> Not works.
> 
> ```
>     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:?]
>     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:?]
>     at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:883) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
>     at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:51) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:?]
>     at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.20.1.jar%23146!/:?]
>     at net.minecraft.commands.Commands.m_242674_(Commands.java:321) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1871) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:1835) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
>     at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1029) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1012) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1006) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:992) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:908) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
>     at java.lang.Thread.run(Thread.java:833) [?:?]
> ```
> 
> Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component org.bukkit.scoreboard.Team.displayName()' at dev.groovin.teamsexpansion.PluginKt.getGetDisplayName(Plugin.kt:73) ~[?:?] at dev.groovin.teamsexpansion.PluginKt.access$getGetDisplayName(Plugin.kt:1) ~[?:?] at dev.groovin.teamsexpansion.TeamsExpansion.onRequest(Plugin.kt:32) ~[?:?] at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?] at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?] at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118) ~[PlaceholderAPI-2.11.6.jar:?] at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-2.11.6.jar:?] at me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-2.11.6.jar:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[forge-1.20.1-47.3.1-universal.jar%23349!/:?] ... 22 more
> 
> >

it works perfectly with other placeholders, but not with display name ( i tried 2.11.6 and 2.11.5)

**Comment by Groovin-Dev** [comment]
Can you post the full text component you are using for the team?

**Comment by andriiqx** [comment]
> Can you post the full text component you are using for the team?

/papi parse andryqx %team_displayname_andryqx%

**Comment by andriiqx** [comment]
> > Can you post the full text component you are using for the team?
> 
> /papi parse andryqx %team_displayname_andryqx%

it's strange, but it works normal with empty non-existent team.. but with real teams.. same error
